[tool.isort]
profile = "black"
src_paths = ["examples", "tests"]

[tool.poetry]
name = "template-python"
version = "0.1.0"
description = "Template repository for Python projects"
authors = ["Brendon Smith <br3ndonland@protonmail.com>"]
license = "MIT"
homepage = "https://github.com/br3ndonland/template-python"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
flake8 = "*"
mypy = "*"
pre-commit = "^2.6"
pytest = "^5.4"

# Pytest v6 will use [pyproject.toml](https://docs.pytest.org/en/latest/customize.html)
[tool.pytest.ini_options]
addopts = "-q"
minversion = "6.0"
testpaths = ["tests"]

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
