[tool.isort]
profile = "black"
src_paths = ["templatepython", "tests"]

[tool.poetry]
name = "templatepython"
version = "0.1.0"
description = "Template repository for Python projects"
authors = ["Brendon Smith <br3ndonland@protonmail.com>"]
license = "MIT"
homepage = "https://github.com/br3ndonland/template-python"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
flake8 = "*"
isort = "^5.6.1"
mypy = "*"
pre-commit = "^2.7"
pytest = "^6.1"
pytest-mock = "^3"

[tool.pytest.ini_options]
addopts = "-q"
minversion = "6.0"
testpaths = ["tests"]

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
