name: tests

on:
  pull_request:
  push:
    branches: [master, develop]
    paths:
      - "**.lock"
      - "**.py"
      - "**.toml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Run unit tests
        run: pytest
